#!/bin/sh
# this is an example installation of a maven repo file
mvn install:install-file \
  -Dfile=swt.jar \
  -DgroupId=org.eclipse.swt \
  -DartifactId=swt-carbon-macosx \
  -Dversion=3.6 \
  -Dclassifier=x86 \
  -Dpackaging=jar \
  -DlocalRepositoryPath=/var/www/maven2 \
  -DcreateChecksum=true
